# Copyright 2021 Creu Blanca
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

from odoo import api, fields, models, _

class HrEmployeeMaterialRequest(models.Model):

    _inherit = 'hr.employee.material.request'

    location_id = fields.Many2one('stock.location', ondelete="cascade", required=True)
    procurement_group_id = fields.Many2one(
        'procurement.group', 'Procurement Group', readonly=True,
        states={'draft': [('readonly', False)]},
        help="Moves created through this stock request will be put in this "
             "procurement group. If none is given, the moves generated by "
             "procurement rules will be grouped into one big picking.",
        default=lambda self: self._default_procurement_group_id())

    def _default_procurement_group_id(self):
        group_id = self.env['procurement.group'].create({
            'move_type': 'direct',
            'material_request_id': self.id,
            'partner_id': self.employee_id.user_id.partner_id
        })
        return group_id

    @api.onchange('procurement_group_id', 'line_ids')
    def onchange_procurement_group_id(self):
        for line in self.line_ids:
            line.procurement_group_id = self.procurement_group_id

    def accept_request(self):
        for rec in self:
            if rec.line_ids:
                for line in self.line_ids:
                    line._action_launch_procurement_rule()
        super().accept_request()
